/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class maths_Armadillo */

#ifndef _Included_maths_Armadillo
#define _Included_maths_Armadillo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     maths_Armadillo
 * Method:    spsolve
 * Signature: (Ljava/nio/DoubleBuffer;Ljava/nio/IntBuffer;Ljava/nio/IntBuffer;Ljava/nio/DoubleBuffer;Ljava/nio/DoubleBuffer;)V
 */
JNIEXPORT void JNICALL Java_maths_Armadillo_spsolve
  (JNIEnv *, jclass, jobject, jobject, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
